### ISSUE TITLE
Idea/Addon

### ISSUE THREAD

**Issue by MickeyMouseYT** [remplerus/StoneUtilities#3]
Hello !

Like i have some suggestion :

To Do :
- Fix Hopper Stone ( 3 slots only )

Idea :
(Maybe add)

/Tools/

- Stone Shear ? 
- Stone Bucket ? ( Try with durability ? And it will again more damage quick when using a fluid hot ? )
- Stone Horse Armor ?
- Stone Armor ?
- Stone Bow ?
- Stone Crossbow ?
- Stone Backpack ? ( only 12 slots ? for storage )
- Stone Fishing Rod ?
- Stone Boat ?
- Stone Shield ?

- Stone Hopper Minecart ?
- Stone Chest Minecart ?

/Item/

- Stone Bowl ( idk what it will with ... )

/Block/

- Stone Trapped Chest ?
- Stone Chest ?
- Stone Barrel ?
- Stone Composter ?
- Stone Bars ?
- Stone Trappe ?
- Stone Torch ?
- Stone Lamp ? ( i think it's already in Quark )
- Stone Crafting Table Slab ?
- Stone Sign ?
- Stone Bed ?
- Stone Item Frame ?
- Stone Fence ?
- Stone Fence Gate ?
- Stone Door ?
- Stone Lectern ?
- Stone Bookshelf ?
- Stone Beehives ?

/Addon/

- Stone Table ?
- Stone Chair ?
- Stone Stool ?

- Stone Plate ?
- Stone Gear ?

- Stone Window ? ( support for create )

/Other/

- Maybe you try make like https://www.curseforge.com/minecraft/mc-mods/i-like-wood for any tools with your stick stone ?

Have a good day.
MickeyMouseYT

**Comment by remplerus** [comment]
noticed, please have some patience as i dont have much time atm

**Comment by MickeyMouseYT** [comment]
> noticed, please have some patience as i dont have much time atm

Np Take Your Time

**Comment by remplerus** [comment]
Stone Hopper and Stone hopper minecart are added to new 1.16.5 beta version.
Ideas added to todo list:
- shear
- armor
- torch
- gear
- stone wall gate

things i don't add:
- stone chest (as there is already a well known and used mod) and it's equivalents
- stone fence, fence gate, door, bed and anything you have listed at "addon" as that doesn't fit in stoneblock (maybe a new mod should be build for those things)
- stone bucket (have you ever seen a bucket out of stone?)

everything else might be added in the future

**Comment by remplerus** [comment]
but thanks for the ideas i could add to the mod, closing it with this comment

**Comment by MickeyMouseYT** [comment]
> Stone Hopper and Stone hopper minecart are added to new 1.16.5 beta version. Ideas added to todo list:
> 
> * shear
> * armor
> * torch
> * gear
> * stone wall gate
> 
> things i don't add:
> 
> * stone chest (as there is already a well known and used mod) and it's equivalents
> * stone fence, fence gate, door, bed and anything you have listed at "addon" as that doesn't fit in stoneblock (maybe a new mod should be build for those things)
> * stone bucket (have you ever seen a bucket out of stone?)
> 
> everything else might be added in the future

it exist of bucket stone like :

![image](https://user-images.githubusercontent.com/78499313/168421551-1ff4c0cf-b34a-4893-8732-118db5db309e.png)

and for chest you can me say what is the mod who have it ?

**Comment by remplerus** [comment]
https://www.curseforge.com/minecraft/mc-mods/stone-chest

**Comment by MickeyMouseYT** [comment]
> https://www.curseforge.com/minecraft/mc-mods/stone-chest

Ah thank you sorry again.

**Comment by MickeyMouseYT** [comment]
So for stone bucket it's still no ?

**Comment by MickeyMouseYT** [comment]
And for stone chest mod it's a bit disappointed because it's the same as a wooden chest I would like it to be different maybe stone is better than wood and it haven't a file config.

**Comment by MickeyMouseYT** [comment]
![image](https://user-images.githubusercontent.com/78499313/168451624-c32f1585-4a4c-490d-96ad-28a473639389.png)

incorrect name of item

**Comment by MickeyMouseYT** [comment]
And stone torch haven't recipe for make it. ( too for wall stone gate )
