### ISSUE TITLE
Progressing project?

### ISSUE THREAD

**Issue by MickeyMouseYT** [remplerus/StoneUtilities#4]
Hello, as I prove to you a photo so that the stone bucket does exist in real life, so are you going to add it or not? You didn't answer my question. And I see that this project is not progressing?

**Comment by remplerus** [comment]
if you want, you can develop it too as i dont have always time and mood to work on the mod.

**Comment by MickeyMouseYT** [comment]
I can help you with stone bucket or others drawing if you want but I don't know very well how to develop
